[package]
name = "musicli"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.2"
anyhow = "1.0.104"
tracing = "0.1.44"
tokio = "1.53.1"
rodio = "0.22.2"
mlua = { version = "0.12.0", features = ["lua55", "vendored", "serialize"] }
dirs = "6"
color-eyre = "0.6.5"
crossterm = "0.29.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
sha2 = "0.10"
base64 = "0.22"
rand = "0.8"
webbrowser = "1"
libc = "0.2"
